import { ReduxProviders } from "@src/redux/provider";

import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <ReduxProviders>{children}</ReduxProviders>
            </body>
        </html>
    );
}
